replicaCount: 2

image:
  tag: latest
  pullPolicy: Always

env:
  SERVICE_NAME: catering
  LOG_LEVEL: info

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
