#!/usr/bin/env python3
"""Regenerate the notional store inventory.

The BurritoWorks store estate is described by a store list (site id, region,
market, address block). This script expands it into the Ansible inventory the
network and edge playbooks run against. It is committed so the inventory in
`inventories/stores/` can be reproduced, not hand-edited.
"""

from __future__ import annotations

import pathlib
import random

REGIONS = {
    "west": {"markets": ["san-diego", "los-angeles", "phoenix", "denver", "seattle"], "asn": 64901},
    "central": {"markets": ["dallas", "austin", "chicago", "minneapolis", "kansas-city"], "asn": 64902},
    "east": {"markets": ["new-york", "boston", "atlanta", "orlando", "columbus"], "asn": 64903},
}

STORES_PER_MARKET = 20
OUTPUT = pathlib.Path(__file__).parent / "inventories" / "stores" / "hosts.yml"


def main() -> None:
    random.seed(1704)
    lines: list[str] = [
        "# GENERATED by generate_inventory.py -- do not hand edit.",
        "all:",
        "  children:",
    ]

    site_number = 100
    for region, meta in REGIONS.items():
        lines.append(f"    region_{region}:")
        lines.append("      children:")
        for group in ("store_edge_routers", "store_kitchen_hosts", "store_pos_gateways"):
            lines.append(f"        {region}_{group}:")
            lines.append("          hosts:")
            counter = site_number
            for market in meta["markets"]:
                for index in range(STORES_PER_MARKET):
                    site = counter + index
                    octet_a = 10
                    octet_b = 100 + list(REGIONS).index(region)
                    octet_c = site % 250
                    host_offset = {
                        "store_edge_routers": 1,
                        "store_kitchen_hosts": 20,
                        "store_pos_gateways": 30,
                    }[group]
                    short = {
                        "store_edge_routers": "rtr",
                        "store_kitchen_hosts": "kds",
                        "store_pos_gateways": "pos",
                    }[group]
                    lines.append(f"            store{site}-{short}:")
                    lines.append(f"              ansible_host: {octet_a}.{octet_b}.{octet_c}.{host_offset}")
                    lines.append(f"              site_id: '{site}'")
                    lines.append(f"              market: {market}")
                    lines.append(f"              region: {region}")
                counter += STORES_PER_MARKET
        site_number = counter

    for group in ("store_edge_routers", "store_kitchen_hosts", "store_pos_gateways"):
        lines.append(f"    {group}:")
        lines.append("      children:")
        for region in REGIONS:
            lines.append(f"        {region}_{group}: {{}}")

    OUTPUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUTPUT}")


if __name__ == "__main__":
    main()
