replicaCount: 3

image:
  repository: burritoworks/catering
  tag: 0.9.7
  pullPolicy: IfNotPresent

env:
  SERVICE_NAME: catering
  LOG_LEVEL: warn

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 512Mi
